"use server"
import nodemailer from "nodemailer"
const MAIL_FROM = process.env.MAIL_FROM
const MAIL_TO_CONTACT = process.env.MAIL_TO_CONTACT
const MAIL_FROM_PASSWORD = process.env.MAIL_FROM_PASSWORD

const transporter = nodemailer.createTransport({
  service: "Gmail",
  auth: {
    // TODO: replace `user` and `pass` values from <https://forwardemail.net>
    user: MAIL_FROM,
    pass: MAIL_FROM_PASSWORD,
  },
});
export async function contactMail(data: any) {
  try {

    const info = await transporter.sendMail({
      from: MAIL_FROM, // sender address
      to: MAIL_TO_CONTACT, // list of receivers
      subject: `Contact Details From ${data.get("name")} `, // Subject line
      text: `{
                "Full Name": ${data.get("name")},
                "Email": ${data.get("email")},
                "Phone": ${data.get("phone")},
                "Subject": ${data.get("subject")},
                "Message": ${data.get("message")},

            }`, // plain text body
      html: `<!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Job Application</title>
              <style>
                body {
                  font-family: Arial, sans-serif;
                  background-color: #f4f4f4;
                  padding: 20px;
                  text-align: center;
                }
            
                h1 {
                  color: #333;
                }
            
                h5 {
                  color: #555;
                  margin-top: 20px;
                }
            
                p {
                  margin-bottom: 20px;
                }
              </style>
            </head>
            <body>
              <h1>Contact Details</h1>
              <p>Here are the details:</p>
            
              <h5>
                Full Name: ${data.get("name")} <br>
                Email: ${data.get("email")} <br>
                Phone: ${data.get("phone")} <br>
                Subject: ${data.get("subject")} <br>
                Message: ${data.get("message")} <br>

              </h5>
            
              <p>This this Autogenerated Mail.</p>
              <p>Best regards,<br>
              Brookside</p>
            </body>
            </html>`,
    });
    return { sucess: true }
  } catch (error: any) {
    return { error: error.message }
  }

}

export async function AdmissionMail(data: any) {
  try {

    const info = await transporter.sendMail({
      from: MAIL_FROM, // sender address
      to: MAIL_TO_CONTACT, // list of receivers
      subject: `Admission Details From ${data.get("childName")} `, // Subject line
      text: `{
                "Child Name": ${data.get("childName")},
                "Parent Name": ${data.get("parentName")},
                "Email": ${data.get("email")},
                "Mobile Number": ${data.get("mobileNumber")},
                "Grade": ${data.get("grade")},
                "City": ${data.get("city")},


            }`, // plain text body
      html: `<!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Job Application</title>
              <style>
                body {
                  font-family: Arial, sans-serif;
                  background-color: #f4f4f4;
                  padding: 20px;
                  text-align: center;
                }
            
                h1 {
                  color: #333;
                }
            
                h5 {
                  color: #555;
                  margin-top: 20px;
                }
            
                p {
                  margin-bottom: 20px;
                }
              </style>
            </head>
            <body>
              <h1>Contact Details</h1>
              <p>Here are the details:</p>
            
              <h5>
              Child Name: ${data.get("childName")} <br>
                Parent Name: ${data.get("parentName")} <br>
                Email: ${data.get("email")} <br>
                Mobile Number: ${data.get("mobileNumber")} <br>
                Grade: ${data.get("grade")} <br>
                City: ${data.get("city")} <br>


              </h5>
            
              <p>This this Autogenerated Mail.</p>
              <p>Best regards,<br>
              Brookside</p>
            </body>
            </html>`,
    });
    return { sucess: true }
  } catch (error: any) {
    return { error: error.message }
  }

}


